---
github: [devinschumacher]
liberapay: devinschumacher
open_collective: devinschumacher
custom: [
  "https://serp.ai/products/ai-voice-cloner/reviews/",
  "https://serpapps.github.io/ai-voice-cloner",
  "https://devinschumacher.com/",
  "https://serp.co/products/ai-voice-cloner/reviews/"
]
